### ISSUE TITLE
Enable possibility of private filters.

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#117]
What do we need to change/support in our installation flow?

**Comment by Nusiq** [comment]
I don't understand the issue

**Comment by SirLich** [comment]
@Nusiq This is related to filters in private repos. Regolith install will (probably?) fail here, because we don't do any authentication. We need to investigate what `git-getter` provides in this regard, and see if it is possible. 

Otherwise marketplace teams using Regolith can't easily use our installation system for their private filters.

**Comment by Nusiq** [comment]
go-getter internally calls git command. It should work on privat repos

**Comment by Nusiq** [comment]
I just tested that and it works.
