### ISSUE TITLE
Create system that minifies json, and passes it in as an argument

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#12]
As per the title. This would be completely optional, and of course not all filters would even HAVE settings, but I think its really nice:

```json
{
    "run_with": "python",
    "location": "./credit_creator.py",
    "name": "Credit Creator",
    "settings": {
        "identifier": "sirlich"
    }
}
```

Gets called like:
`python -u credit_creator.py '{"identifier":"sirlich"}'`

**Comment by stirante** [comment]
Added initial implementation in https://github.com/Bedrock-OSS/regolith/commit/21b33ee496552bd1f20ed726d2fe395970b3f656

**Comment by stirante** [comment]
Closing due to no comments
