### ISSUE TITLE
Investigate installing regolith

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#13]
What does it look like to download and use regolith for the random user?

Can they rely on `regolith` gopath thing, or do they need to include an `.exe` in every project. 

What can we do to make this process awesome and easy?

**Comment by Luminoso-256** [comment]
we could probably throw together a simple installer which throws regolith (and an auto-updater?) in a Program Files/<something> directory, and then adds regolith to the path. meaning they can use it wherever. I'm hesitant to rely on the gopath, as needing Golang installed should not be a usage requirement in my opinion

**Comment by stirante** [comment]
Partially added in https://github.com/Bedrock-OSS/regolith/commit/bb1b6af352c883958f6f43a0aa91cba11d72deac
Currently generates MSI installer for windows, but fails to generate it in GitHub Action.
