### ISSUE TITLE
Design format + write logic for export locations

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#14]
Can build upon the base in `minecraft_utils.go`. 

I guess we want these targets:
 - [x] exact (filepath)
 - [x] dev packs (requires a definition for the name of the RP and the BP, after exporting) 
 - [x] world (same req as above)
 - [x] none (just leave in `build`)

**Comment by SirLich** [comment]
`develop` export is done, but we need more options.

**Comment by Nusiq** [comment]
`develop` is the "dev packs" from the description from the first message.
