### ISSUE TITLE
Add safeguard for data files

### ISSUE THREAD

**Issue by stirante** [Bedrock-OSS/regolith#161]
While having windows explorer open with `packs/data/gametests` folder, I ran regolith, which failed with error:
```
[INFO]  Moving files to target directory.
[ERROR] Failed to run profile "dev"
[+]: Exporting project failed.
[+]: Failed to clear filter data path "./packs/data".
[+]: remove ./packs/data\gametests: The process cannot access the file because it is being used by another process.
```

This caused `packs/data` folder to become empty (except for empty `gametests` folder), while the data files were still in `.regolith/tmp/data`.

Thinking, that the issue will fix itself, I ran it again and regolith removed `.regolith/tmp` and copied empty `data` folder there, which resulted in loosing data folder completely (fortunately I still had the changes on git).

Since any error regarding clearing filter data or moving filter data back to the `packs` folder results in potential data loss, I suggest adding some kind of safeguard to it as well as clear message to the user.

## Suggestion

After error, that might result in potential data loss, we should display a clear message to the user like 
```
The data folder might potentially be corrupted, please copy them from .regolith/tmp/data to packs/data manually.
```
Additionally we could save a json file inside `.regolith` folder with information about it and in case a user wouldn't notice this message, we would block any further executions of regolith with message 
```
The data folder might potentially be corrupted, please copy them from .regolith/tmp/data to packs/data manually. 
If you already did it, run regolith again with --force flag
```
The `--force` flag would remove that json file or modify it to clear the information and run regolith normally.

**Comment by stirante** [comment]
Seems like RecycledCopyOrMove feature has mostly fixed issues like these from happening again.

**Comment by Nusiq** [comment]
![image](https://user-images.githubusercontent.com/34062025/182129329-309e3b75-32f4-4581-af72-ea6a991c2b0b.png)

**Comment by Nusiq** [comment]
I accidentally duplicated this issue (#183). It is solved now.
