### ISSUE TITLE
Add `regolith run --filter <filter name>` 

### ISSUE THREAD

**Issue by Nusiq** [Bedrock-OSS/regolith#191]
This command would let you run only one filter. It could be useful for debuging. It's faster than disabling filters or cerating profiles with single filter. It would be also useful with `--inplace` flag described in issue #190.

**Comment by SirLich** [comment]
Regardless of my thoughts on the `--in-place` flag, I'm a fan of this command :)

One question: Will it allow specifying many filters?

i.e., `regolith run --filter name_ninja json_cleaner`

**Comment by Nusiq** [comment]
Closed and replaced with an alternative idea (#201).
