### ISSUE TITLE
Add `regolith exec <filter-name> [arguments...]` command

### ISSUE THREAD

**Issue by Nusiq** [Bedrock-OSS/regolith#201]
This idea is a result of a discussion about #191 and #190 on discord.

The `exec` command will be able to run filters on the source files of the project. The filters that are intended for this purpose will need to specify that in their `filter.json` file using new property - `canModifySource` (the name of the property is yet to be decided).

The user will be able to force non-exec filters to be used that way by using the `--force` flag.

**Comment by SirLich** [comment]
I think the best way to ship this feature is by treating as a true feature, and not as a side-consequence of flags. 

Once we have good "branding" for the idea, we can then name things like 'canModifySource' , the name of the command, and then also include docs and stuff. 

The more I think about it, the more I wonder whether `tool` is the right branding. 

We could get:
 - `regolith run-tool ...`
 - And filter property is `isToolScript`

**Comment by Nusiq** [comment]
I like it. We can it call with these names.

**Comment by Nusiq** [comment]
This issue is closed with #220. The command is called `regolith tool`
