### ISSUE TITLE
`RP` and `BP` folders aren't auto-saved in git repo, causing warning after cloning

### ISSUE THREAD

**Issue by mark-wiemer** [Bedrock-OSS/regolith#212]
1. `regolith init` in a repo
2. Create a resource pack (but not a behavior pack)
3. `regolith run` should work
4. Commit and push changes
5. Clone the repo
6. `regolith install-all`
7. `regolith run`

Expected: No warnings

Actual: `[WARN]  resource folder "./packs/BP" does not exist`

Notes: If `regolith init` added a [`.gitkeep` file](https://www.freecodecamp.org/news/what-is-gitkeep/) to `RP` and `BP` we wouldn't have this problem as they'd be copied over in the clone :)

**Comment by SirLich** [comment]
The .gitkeep file would be the classic way to do this, but at the same time, it would be a bit annoying to have exported into your com.mojang folder. 

Does it work OK to remove the relevant line from the `config.json`? If that works, i think it would be reasonable that single-pack projects simply adjust their config.json to match their usage.

**Comment by mark-wiemer** [comment]
Yeah, that makes sense too. I guess I was thinking a filter would ignore the `.gitkeep` file. I just started using Regolith yesterday, I figured simple projects should be able to compile without warnings, so that's the main goal. Whether it's auto-updating `config.json` or something else, it should be easy to share source code and have others compile it with without warnings

**Comment by SirLich** [comment]
Yeah for sure. Feel free to add your own `.gitkeep` file there. Just be aware the .gitkeep file will show up in the final export. 

The `regolith init` command is also under review anyways, since we eventually want to upgrade it to include some other stuff, like maybe cloning a template project, or even just creating linked manifest files.

**Comment by Nusiq** [comment]
Once we add 
egolith init --full which creates entire project will, this won't really be a problem. If you're working on a project which has only RP you can remove the RP property from the *config.json* file and you won't get this warning anymore.
