### ISSUE TITLE
Remote filters won't copy data unless data folder exists before running

### ISSUE THREAD

**Issue by evilguy50** [Bedrock-OSS/regolith#249]
After setting up the exportData key on a remote filter.json the data will never export unless a per-existing data folder is included before runtime. filter data created during tmp runtime without per-existing filter data folder won't get exported.

**Comment by Nusiq** [comment]
Link to a message that started a discussion about it on discord: https://discord.com/channels/494194063730278411/896876881410936853/1057423678972891216
