### ISSUE TITLE
More flexible support of pack export locations

### ISSUE THREAD

**Issue by MeItsLars** [Bedrock-OSS/regolith#250]
**Observation**:
Right now, we have the export targets as mentioned on [the wiki](https://bedrock-oss.github.io/regolith/guide/export-targets/).

**Problem**:
This system is slightly messy and doesn't allow for exporting to:
- specific worlds in preview edition
- anything in Minecraft: Education Edition

As there is no support for %AppData%, it is also not possible to include these directories via an `exact` export.

**Proposed solution**:
There are various solutions that are possible here. A very simple solution is adding support for including %AppData% in paths, but you can also rework the system a bit more. Examples include a configuration system like this (as proposed on the Discord):

Exporting to local:
```json
"export": {
  "target": "local"
}
```

Exporting to an exact location:
```json
"export": {
  "target": "exact",
  "rpPath": "...",   // Possibly including %AppData%
  "bpPath": "..."    // Possibly including %AppData%
}
```

Exporting to any development folder:
```json
"export": {
  "target": "development",
  "minecraftEdition": "default", "preview", "education"   // OPTIONAL: Defaults to 'default'
}
```

Exporting to any world via a world name:
```json
"export": {
  "target": "world",
  "worldName": "...",
  "minecraftEdition": "default", "preview", "education"   // OPTIONAL: Defaults to 'default'
}
```

Exporting to any world via a world path:
```json
"export": {
  "target": "world",
  "worldPath": "..."  // Possibly including %AppData%
}
```

**Comment by stirante** [comment]
Support for environment variables has been added.
