### ISSUE TITLE
Add option to force project initialisation

### ISSUE THREAD

**Issue by MeItsLars** [Bedrock-OSS/regolith#257]
### Observation
Initialising a new Regolith project is only possible in an empty directory.

### Problem
This is not practical in situations when a directory already contains some files that are not harmful to Regolith. Examples include .git directories and readme files.

### Suggested solution
Add a --force option to the regolith init command that also allows for project initialisation in non-empty directories. Any unintended consequences of this command would be the user's responsibility.

**Comment by stirante** [comment]
Done in #258
