### ISSUE TITLE
Add user config to override `com.mojang` path

### ISSUE THREAD

**Issue by ink0rr** [Bedrock-OSS/regolith#260]
This is mainly for working on a non-Windows platform, an example case would be when using [mcpelauncher](https://mcpelauncher.readthedocs.io/en/latest/) on macOS, where the default `com.mojang` path is `$HOME/Library/Application Support/mcpelauncher/games/com.mojang`.

It's technically possible to just use the `exact` mode for it, but that means I have to setup a different export profile for every OS in every project, which is not ideal.

**Comment by SirLich** [comment]
> but that means I have to setup a different export profile for every OS in every project, which is not ideal.

I agree this isn't ideal. One thing that can make this a little easier is to use the "profile" filter type. 

So you can have:
 - profile main (all filters)
 - profile windows (main profile + export)
 - profile linux (main profile + export)
 
 This is still less practical than making 'development' and 'preview' targets work on Linux, but it's a start.
