### ISSUE TITLE
Argument field does not work in config.json

### ISSUE THREAD

**Issue by SmokeyStack** [Bedrock-OSS/regolith#268]
https://bedrock-oss.github.io/regolith/guide/configuration

Im passing an argument to a filter that uses shell however it wont pass the argument. If I use the argument field in the filter.json, it works.

**Comment by stirante** [comment]
Can you provide an example?

**Comment by SmokeyStack** [comment]
Using my [filter](https://github.com/SmokeyStack/adk/tree/refactor), if I put the arguments field in the `filter.json` it will output Hello World. However, if I remove the arguments field from the `filter.json`, and add
```json
"filters": [					{
    "filter": "adk",
         "arguments": [
	     "Hello world but from config"
         ]
    }
]
```
to my config.json, it will just out put ECHO is on

**Comment by SmokeyStack** [comment]
Seems to be fixed in the latest regolith version
