### ISSUE TITLE
[Design decision] Handling virtual environments for Python

### ISSUE THREAD

**Issue by Nusiq** [Bedrock-OSS/regolith#28]
This issue will be used as a thread to discuss the possible changes to `venvPath` setting.

# Current implementation
Regolith `config.json` file has currently 4 depth levels.
1. Root - defined by the [Bedrock-OSS/project-config-standard](https://github.com/Bedrock-OSS/project-config-standard)
2. "regolith" - the root of the regolith configuration
3. "profiles" - a list of profiles. A profile is a single task that you can trigger with `regolith run` command
4. "filters" - a filter is a single action within the profile (it can be a python, js or shell script)

Currently the `venvPath` is a property of a profile. **Adding that configuration** to the file will cause creation of a single python environment for all filters in the profile. **Skipping that property** will (the default behavior) creates separate `venv` for every filter in `.regolith/cache/<filter path>/venv`.

`venvPath` can be either relative or absolute path. If user choose to put relative path in there it will create the virtual environment in a path relative to `.regolith/venvs/`.

# Problems
## 1. Where in the `config.json` should we put the `venvPath` property
1.1. It should be the property for entire project (inside "regolith")
1.2 It should be the property of a profile (regolith -> profiles -> [profile name]). This is the current solution.
1.3 It should be the proprety of a filter (regolith -> profiles -> <profile name> -> filters -> [filter name]).
## 2. If the path is relative, what should be the root
2.1. `.regolith/venvs/<user path>` - This is the current solution
2.2. `.regolith/cache/<user path>` - The problem of this solution is that we already use `.regolith/cache/<filter name>` for caching filters. If someone choose to name the `venv` the same as the filter it could create some collisions.
2.3 `.regolith/cache/venvs/<user path>` - with this solution i suggest moving the filter cache from `.regolith/cache/<filter name>` to `.regolith/cache/filters/<filter name>`.
## 3. What should be the default behavior
3.1. Separate `venv` for every filter - This is the current solution
3.2. Separate `venv` for every profile
3.3. Everything should use single venv
## 4. Should we allow absolute paths
4.1. Yes
4.2. No

**Comment by Nusiq** [comment]
My favourite solution is:
- 1.3 - use `venvPath` as filter setting
- 2.3 - use `cache/venvs` and `cache/filters` paths
- 3.2 - separate `venv` for every profile. I would put it `.regolith/cache/venvs/<profile name>`
- 4.2 - No. Absolute paths make probles with `regolith clean` command.

The downside of this solution is that someone could put a name of a profile into `venvPath` which would cause a filter to use a default `venvPath` of a profile.

**Comment by stirante** [comment]
My choices are:
 - 1.1
 - 2 - I think all the paths should be relative to the project root, because otherwise it creates confusion
 - 3.3
 - 4.2 - anyways even with relative paths it might be problematic ( `../../../../../../../here` )

**Comment by Nusiq** [comment]
The problems with relative paths can be simply avoided by checking for `..` in the path

**Comment by SirLich** [comment]
OK, lets start with the most important one:

3.3: The entire project should use a shared venv, somewhere in the cache. This is the best, strongest, default behavior. 

1.3: IF we go with 3.3, then we need to make this "venvPath" very powerful, to allow it to "fix" filters broken by the shared venv. Per-filter is the most powerful. 

2: I don't care. But I do support the reorganization shown in 2.3 (adding a `filters` folder in cache)

4: No opinion.

---


I also suggest replacing the "venvPath" argument with a bool, called useCustomVenv, which automatically creates and handles the venv creation + path. 

I don't think we need as much power as this "venvPath" argument.

**Comment by Nusiq** [comment]
> 
> 
> OK, lets start with the most important one:
> 
> 3.3: The entire project should use a shared venv, somewhere in the cache. This is the best, strongest, default behavior.
> 
> 1.3: IF we go with 3.3, then we need to make this "venvPath" very powerful, to allow it to "fix" filters broken by the shared venv. Per-filter is the most powerful.
> 
> 2: I don't care. But I do support the reorganization shown in 2.3 (adding a `filters` folder in cache)
> 
> 4: No opinion.
> 
> I also suggest replacing the "venvPath" argument with a bool, called useCustomVenv, which automatically creates and handles the venv creation + path.
> 
> I don't think we need as much power as this "venvPath" argument.

I think I like that. So to summarize the idea and to specify some things you didn't talk about - here is how I would implement that:
- If there is at least one python filter without `useCutomVenv` a project venv will be created in `.regolith/cache/venv`
- The python filters with `useCustomVenv` property will create their own venvs in `.regolith/cache/customVenvs/<filter name>`.
    - There is a potential problem here because the name of a filter might not be a valid name of the folder. We might use a hash function to generate alternative names for filters like that
-  We will move the filter cache from `.regolith/cache/<filter name>` to `.regolith/cache/filters/<filter name>`.

This solution also removes the option of writing absolute paths.
-----------------------------------------
Alternative Idea:
- `venvSlot` - integer. 0 by default. The the venv folder would be created in `.regolith/cache/venvs/<venv slot>`. By default everything would have slot 0 so the default venv would be `.regolith/cache/venvs/0/`

**Comment by stirante** [comment]
> I also suggest replacing the "venvPath" argument with a bool, called useCustomVenv, which automatically creates and handles the venv creation + path.
> 
> I don't think we need as much power as this "venvPath" argument.

I agree here with simplifying venv handling

**Comment by Nusiq** [comment]
Final decision from discord:
```
- We're adding a new proeprty to filters called venvSlot: int. The default value of the venvSlot is 0
 - The venvs will be created in .regolith/cache/venvs/<venvSlot>.
 - We will move the filter cache from .regolith/cache/<filter name> to .regolith/cache/filters/<filter name>.

So by default all of the filters will use the venv from  .regolith/cache/venvs/0 and the user won't be able to specify the venv path outside the project.
```
