### ISSUE TITLE
Improve error messaging: no more tracebacks for Regolith-handled errors. 

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#29]
Related to #22. 

We need to provide a traceback of course, if requested, but many of our errors are currently producing a tracback, even when they really shouldn't. 

For example, running `regolith run` without `regolith init` will cause a very yucky error, that is difficult to interpret. In these cases, we should write a clear, concise error, with instructions on what to do next:

![image](https://user-images.githubusercontent.com/18729296/131471208-14d2bc41-5ce8-4a82-88da-891834fc022e.png)

**Comment by stirante** [comment]
Errors are refactored to give a bit of human stack trace and `--debug` flag added.
