### ISSUE TITLE
Regolith cannot be used without git

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#30]
What do we want to do here?

```
Could not install dependency github.com/Bedrock-OSS/regolith-filters//texture_list: error downloading 'https://github.com/Bedrock-OSS/regolith-filters.git': git must be available and on the PATH
```

**Comment by SirLich** [comment]
Maybe we should have a `regolith check` command, that runs some health-checks, and provides checklist of user-actions like "install git", if Regolith isn't healthy?

**Comment by Nusiq** [comment]
Can't we check that in `regolith install`?

**Comment by SirLich** [comment]
Yes, I suppose! In that case, relates to #29

**Comment by stirante** [comment]
Optionally we can create a downloader, that is independent from git

**Comment by SirLich** [comment]
The repo for golang downloads is so nice tho

**Comment by stirante** [comment]
Added downloader that doesn't require git and added go-getter as a fallback in https://github.com/Bedrock-OSS/regolith/commit/c3a4102c06f4986b70abb79e08b0241cffe246cf
