### ISSUE TITLE
Things to discuss about "world" export target

### ISSUE THREAD

**Issue by Nusiq** [Bedrock-OSS/regolith#40]
I implemented the "world" export target (for issue #14) but we haven't decide how to handle some cases. Current implementation is very simple.

The "world" export target requires exactly one of the two properties "worldPath" or "worldName". Providing both of them will result in an error.

## Problems
1. In current implementation "worldPath" can lead anywhere. It just creates the some additional folders in that path and exports files there. The folders are `"<worldPath>/behavior_packs/<project_name>_bp"` and `"<worldPath>/resource_packs/<project_name>_rp"`. I'm not sure if that's ok. Maybe the export path should be relative to `.../com.mojang/minecraftWorlds` folder?
2. The exporter doesn't create the `behavior_packs.json` and `resource_packs.json` in the world. Maybe it should?
3. If there is `behavior_packs.json` and/or `resource_packs.json` file in the world and it has a reference to an existing BP/RP should the exporter export files to the path of that reference? What if the file points at a pack inside `development_behavior_packs/development_resource_packs`.

**Comment by stirante** [comment]
IMO exporter should create `*_packs.json` if it doesn't exists and if it exists, it should append packs, that are installed if they're not already added. It shouldn't care whether there are already other packs added etc. 

As for `worldPath` on one hand I think it's redundant and can be removed, but on the other, if we add `*_packs.json` support, then we can't provide it for exact export type.

**Comment by Nusiq** [comment]
I think its fine... right?
