### ISSUE TITLE
Remove `build` folder as a default export 

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#45]
Right now, the build folder is created for all export targets, which doesn't make much sense. 

- [x] Rename `none` to `local`
- [x] Remove `build` directory for all export targets that are not `local`
- [x] Improve efficiency of export by using a MOVE not a COPY (doesn't apply to `local`)

**Comment by Nusiq** [comment]
> Remove build directory for all export targets that are not local
I'm not sure what do you mean. If the export target isn't local the `build` directory is not created

**Comment by Nusiq** [comment]
> Improve efficiency of export by using a MOVE not a COPY (doesn't apply to local)

It does apply to local. `.regolith/tmp` is moved to `build` (just like it did before)
