### ISSUE TITLE
Write `regolith install --update`

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#59]
Updated requirement:

`regolith install --update` will reinstall ALL filters that are version miss-matches. 

i.e., if filter A is 1.0.1, but the installed version is 1.0.0, then `regolith install --update` will reinstall it. 

As normal, the `regolith install` command will skip installed filters.
---
OLD DESCRIPTION:

See #58 

Potential command syntax:
 - `regolith update`
 - `regolith install --update`
 - `regolith update json_cleaner`
 - `regolith install json_cleaner --update`

These are all just concepts though. What we must target is:
 - Ability to install new filters without updating all old filters
 - Ability to update filters when needed (all at once)
 - Ability to pick WHICH filters to update

**Comment by SirLich** [comment]
We need some concept of whether a filter is outdated.

**Comment by Nusiq** [comment]
After some discussion this feature is implemented as `regolith update`
