### ISSUE TITLE
Improve name/description flow of Filters

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#68]
Right now we allow the 'name' field, which is a bit weird, since the real "name" of the filter is of course its actual folder name. 

For example, lets talk about the filter "json_cleaner"

OLD:
 - name: "Cleaning json files..."
 - Description: none
 
 NEW:
  - new: (auto detected) json_cleaner
  - description: "Cleaning json files..."

---

Example of using a few filters:

LOCAL (or remote definition)
{
   "runWith": "python",
   "script": "./bob.py",
   "description": "Printing bob" (optional)
}

REMOTE RUN:
{
   "filter": "bob"
}

**Comment by MedicalJewel105** [comment]
Improved filter descriptions in my latest pr.
