### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#69]
Right now, we have some things set per-filter. This could get annoying, since I guess usually these settings will be the same. Example: `dataPath`.

The solution is to allow profile-specific data to be set in the top level. The properties inside individual profiles therefore only overrides these values. 

This is a really nice flow I used in Echo:NPC.

**Comment by Nusiq** [comment]
The `dataPath` is now part of the `regolith` in config.json file. There is no `dataPath` in profile anymore. I don't think we need that especially after we added `installationos` to `regolith` (#133). `installations` need to know the `dataPath` to be able to be installed so it must be outside of profiles.
