### ISSUE TITLE
Write run-target for javascript. 

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/regolith#9]
Our current implementation is pretty strict in what can be run. Right now, only Python. 

The reason we have unique run-targets for each language instead of just running arbitrary shell command is because its safer, and because it allows us to add additional logic as-needed, for example `-u` for python to enforce the buffer to flush.

**Comment by stirante** [comment]
Done in https://github.com/Bedrock-OSS/regolith/commit/84c3d736ccf2df33b198c1b9dae903f529d27936
